### ISSUE TITLE
Task list for DIGR team members for the ARM Summer School

### ISSUE THREAD

**Issue by scollis** [ANL-DIGR/arm-summer-2018#3]
- [ ] Create an environment file for a nice Python env for ARM data @scollis
- [ ] Create a "How to install a python stack" @scollis

Group 1 tasks
- [ ] Create a notebook on KAZR VPT reading and plotting and a little playing around @zssherman
- [ ] write code in python for reading in KAZR spectra data. I suggest X-Array. It would be very cool if we could write code to take moments of the spectra data and then populate a Py-ART radar object so we can use the VPT visualization. @rcjackson

Group 5 tasks
- [ ] write RST file with instructions on downloading: MWRRET (LWC), TSI, ARSCL and doppler lidar
- [ ] Write a notebook visualizing each for a sample day

**Comment by rcjackson** [comment]
Group 2 tasks:
    * Write a notebook to read in ISDAC microphysical ice size distribution data and CSI bulk water contents from the Convair-580 @rcjackson
